
ALTER TABLE public.marketing_settings
  ADD COLUMN IF NOT EXISTS gsc_verification text,
  ADD COLUMN IF NOT EXISTS bing_verification text,
  ADD COLUMN IF NOT EXISTS pinterest_verification text,
  ADD COLUMN IF NOT EXISTS yandex_verification text,
  ADD COLUMN IF NOT EXISTS pinterest_tag_id text,
  ADD COLUMN IF NOT EXISTS linkedin_partner_id text,
  ADD COLUMN IF NOT EXISTS twitter_pixel_id text,
  ADD COLUMN IF NOT EXISTS reddit_pixel_id text,
  ADD COLUMN IF NOT EXISTS quora_pixel_id text,
  ADD COLUMN IF NOT EXISTS og_site_name text,
  ADD COLUMN IF NOT EXISTS og_default_image text,
  ADD COLUMN IF NOT EXISTS twitter_site_handle text,
  ADD COLUMN IF NOT EXISTS twitter_card_type text,
  ADD COLUMN IF NOT EXISTS hreflang jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS org_legal_name text,
  ADD COLUMN IF NOT EXISTS org_phone text,
  ADD COLUMN IF NOT EXISTS org_email text,
  ADD COLUMN IF NOT EXISTS org_address jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS org_same_as jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS org_slogan text,
  ADD COLUMN IF NOT EXISTS org_founding_date text,
  ADD COLUMN IF NOT EXISTS org_opening_hours jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS ab_experiments jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS robots_txt text,
  ADD COLUMN IF NOT EXISTS fb_capi_pixel_id text,
  ADD COLUMN IF NOT EXISTS fb_capi_access_token text,
  ADD COLUMN IF NOT EXISTS fb_capi_test_event_code text,
  ADD COLUMN IF NOT EXISTS ga4_measurement_id text,
  ADD COLUMN IF NOT EXISTS ga4_api_secret text,
  -- AI search / AEO / GEO / LLM
  ADD COLUMN IF NOT EXISTS ai_brand_description text,
  ADD COLUMN IF NOT EXISTS ai_mission text,
  ADD COLUMN IF NOT EXISTS ai_usps jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS ai_facts jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS ai_founder jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS ai_policy_text text,
  ADD COLUMN IF NOT EXISTS ai_allow_training boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS ai_allow_inference boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS llms_intro text,
  ADD COLUMN IF NOT EXISTS llms_extra_sections jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS geo_latitude numeric,
  ADD COLUMN IF NOT EXISTS geo_longitude numeric,
  ADD COLUMN IF NOT EXISTS geo_service_areas jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS geo_price_range text;

INSERT INTO public.marketing_settings (key) VALUES ('default')
  ON CONFLICT (key) DO NOTHING;
